main:
  - identifier: blog
    name: Cases
    weight: 10
    params:
      icon:
        vendor: fas
        name: blog
  - name: Informations
    identifier: docs
    weight: 200
    params:
      icon:
        vendor: bs
        name: book

  - name: Links
    identifier: links
    weight: 100
    # url: https://github.com/hbstack
    params:
      header: support links
      icon:
        vendor: font-awesome-solid
        name: headset

  # - name: Documentation
  #   parent: links
  #   url: https://hbstack.dev/
  #   weight: 1
  #   params:
  #     icon:
  #       vendor: bs
  #       name: book
  #       className: text-primary
  #     description: The documentation.

  # - name: GitHub
  #   parent: links
  #   url: https://github.com/hbstack
  #   weight: 11
  #   params:
  #     icon:
  #       vendor: fab
  #       name: github
  #     description: The code repository.

  # - name: Discussion
  #   parent: links
  #   url: https://github.com/orgs/hbstack/discussions
  #   weight: 12
  #   params:
  #     icon:
  #       vendor: font-awesome-regular
  #       name: comments
  #       color: green
  #     description: Ask questions and share your ideas.

  # - name: Bug Report
  #   parent: links
  #   url: https://github.com/orgs/hbstack/discussions/new?category=issues-and-bugs
  #   weight: 13
  #   params:
  #     icon:
  #       vendor: font-awesome-solid
  #       name: bug
  #       color: red
  #     description: Tell us about a bug or issue.

  # - name: Feature Request
  #   parent: links
  #   url: https://github.com/orgs/hbstack/discussions/new?category=ideas
  #   weight: 14
  #   params:
  #     icon:
  #       vendor: font-awesome-regular
  #       name: lightbulb
  #       color: orange
  #     description: Suggest new or updated features.
  
  # - name: Mastodon
  #   parent: links
  #   url: https://techhub.social/@hbstack
  #   weight: 16
  #   params:
  #     icon:
  #       vendor: simple
  #       name: mastodon
  #     description: Follow us on Mastodon to get latest updates.
  
  # - name: 플레이스
  #   identifier: place
  #   weight: 500
  #   url: https://naver.me/5AmVd0PR
  #   params:
  #     icon:
  #       vendor: bs
  #       name: phone  
  # - name: 예약
  #   identifier: reserve
  #   weight: 499
  #   url: https://m.booking.naver.com/booking/13/bizes/384022
  #   params:
  #     icon:
  #       vendor: bs
  #       name: bookmark-star  
# footer:
#   - name: Projects
#     identifier: projects
#     weight: 10
#     params:
#       icon:
#         vendor: bootstrap
#         name: boxes
#         color: skyblue
#   - name: HugoPress
#     parent: projects
#     weight: 11
#     url: https://hugomods.com/en/docs/hugopress/
#     params:
#       icon:
#         vendor: simple-icons
#         name: hugo
#         color: "#FF4088"
#   - name: Hugo Docker Images
#     parent: projects
#     weight: 12
#     url: https://hugomods.com/en/docs/docker/
#     params:
#       icon:
#         vendor: simple-icons
#         name: docker
#         color: "#2496ED"
#   - name: Icons
#     parent: projects
#     weight: 13
#     url: https://hugomods.com/en/icons/
#     params:
#       icon:
#         vendor: font-awesome-solid
#         name: icons
#         color: "#F76119"
#   - name: SEO
#     parent: projects
#     weight: 14
#     url: https://github.com/hugomods/seo/
#     params:
#       icon:
#         vendor: font-awesome-solid
#         name: magnifying-glass
#         color: "#87CEEB"
#   - name: Search
#     parent: projects
#     weight: 15
#     url: https://hugomods.com/en/docs/search/
#     params:
#       icon:
#         vendor: bootstrap
#         name: search
#         color: "#712cf9"
#   - name: Bootstrap Shortcodes
#     parent: projects
#     weight: 16
#     url: https://hugomods.com/en/bootstrap/
#     params:
#       icon:
#         vendor: bootstrap
#         name: code-square
#         color: "#712cf9"

#   - name: Support
#     identifier: support
#     weight: 40
#     url: https://github.com/hbstack/
#     params:
#       icon:
#         vendor: font-awesome-solid
#         name: headset
#         color: "#0A5DB9"
#   - name: GitHub
#     parent: support
#     url: https://github.com/hbstack/
#     weight: 41
#     params:
#       icon:
#         vendor: font-awesome-brands
#         name: github
#   - name: Discussion
#     parent: support
#     url: https://github.com/orgs/hbstack/discussions/
#     weight: 42
#     params:
#       icon:
#         vendor: far
#         name: comments
#         color: green
#   - name: Bug Report
#     parent: support
#     url: https://github.com/orgs/hbstack/discussions/new?category=issues-and-bugs
#     weight: 43
#     params:
#       icon:
#         vendor: font-awesome-solid
#         name: bug
#         color: red

#   - name: Feature Request
#     parent: support
#     url: https://github.com/orgs/hbstack/discussions/new?category=ideas
#     weight: 44
#     params:
#       icon:
#         vendor: font-awesome-regular
#         name: lightbulb
#         color: orange